name: flutter_soundboard
description: Flutter-Soundboard

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  shared_preferences:
  audioplayer:
  path_provider:
  stereo:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/short.wav
    - assets/middle.wav
    - assets/long.wav
