name: flutter_soundboard
description: Flutter-Soundboard

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  shared_preferences:
  audioplayer:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/short.wav
    - assets/sounds/middle.wav
    - assets/sounds/long.wav

    - assets/images/short.png
    - assets/images/middle.png
    - assets/images/long.png
